import React from 'react';
import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { afterEach, describe, expect, it, vi } from 'vitest';
import App from './App.jsx';
import LeadScoreCard from './components/LeadScoreCard.jsx';

afterEach(() => vi.restoreAllMocks());
const success = { score: 88, tier: 'Hot', recommendedAction: 'Contact within 24 hours', reasons: ['High intent', 'Enterprise profile', 'Clear buying signal'], risks: ['Budget not confirmed'] };
function mockApi(response = success, ok = true) { return vi.fn().mockResolvedValue({ ok, json: async () => ok ? response : { error: { title: 'AI scoring unavailable', message: 'Service unavailable' } } }); }
async function fillAndSubmit(user, company = 'Acme') { await user.type(screen.getByLabelText('Company name'), company); await user.selectOptions(screen.getByLabelText('Company size'), 'Enterprise'); await user.selectOptions(screen.getByLabelText('Intent'), 'High'); await user.click(screen.getByRole('button', { name: 'Score this lead' })); }

describe('LeadScoreCard', () => { it('renders structured score, tier, action, reasons, and risks', () => { render(<LeadScoreCard result={success} />); expect(screen.getByText('88')).toBeInTheDocument(); expect(screen.getByText('Hot')).toBeInTheDocument(); expect(screen.getByText('Contact within 24 hours')).toBeInTheDocument(); expect(screen.getByText('High intent')).toBeInTheDocument(); expect(screen.getByText('Budget not confirmed')).toBeInTheDocument(); }); });
describe('Signalboard form flow', () => {
  it('validates required form fields', async () => { const user = userEvent.setup(); render(<App />); await user.click(screen.getByRole('button', { name: 'Score this lead' })); expect(screen.getByLabelText('Company name')).toBeInvalid(); });
  it('shows the loading state and prevents duplicate submission', async () => { const user = userEvent.setup(); let resolve; const api = vi.fn(() => new Promise(r => { resolve = r; })); vi.stubGlobal('fetch', api); render(<App />); await fillAndSubmit(user); expect(screen.getByText('Preparing lead details…')).toBeInTheDocument(); expect(screen.getByRole('button', { name: 'Scoring…' })).toBeDisabled(); await user.click(screen.getByRole('button', { name: 'Scoring…' })); expect(api).toHaveBeenCalledTimes(1); resolve({ ok: true, json: async () => success }); });
  it('renders a successful mocked AI result', async () => { const user = userEvent.setup(); vi.stubGlobal('fetch', mockApi()); render(<App />); await fillAndSubmit(user); expect(await screen.findByRole('heading', { name: 'Lead Score Card' })).toBeInTheDocument(); expect(screen.getByText('Contact within 24 hours')).toBeInTheDocument(); });
  it('renders a designed API error without calling Claude directly', async () => { const user = userEvent.setup(); const api = mockApi(null, false); vi.stubGlobal('fetch', api); render(<App />); await fillAndSubmit(user, 'Unavailable Co'); expect(await screen.findByRole('heading', { name: 'AI scoring unavailable' })).toBeInTheDocument(); expect(api).toHaveBeenCalledWith('/.netlify/functions/score-lead', expect.objectContaining({ method: 'POST' })); });
  it('retries the same submitted details', async () => { const user = userEvent.setup(); const api = vi.fn().mockResolvedValueOnce({ ok: false, json: async () => ({ error: { title: 'Temporary error', message: 'Try again' } }) }).mockResolvedValueOnce({ ok: true, json: async () => success }); vi.stubGlobal('fetch', api); render(<App />); await fillAndSubmit(user, 'Retry Co'); await screen.findByRole('button', { name: 'Retry' }); await new Promise(resolve => setTimeout(resolve, 1250)); await user.click(screen.getByRole('button', { name: 'Retry' })); expect(await screen.findByRole('heading', { name: 'Lead Score Card' })).toBeInTheDocument(); expect(api).toHaveBeenCalledTimes(2); expect(api.mock.calls[1][0]).toBe('/.netlify/functions/score-lead'); });
  it('stops a loading request', async () => { const user = userEvent.setup(); vi.stubGlobal('fetch', vi.fn((url, options) => new Promise((resolve, reject) => options.signal.addEventListener('abort', () => reject(Object.assign(new Error('aborted'), { name: 'AbortError' })))))); render(<App />); await fillAndSubmit(user, 'Slow Co'); await user.click(screen.getByRole('button', { name: 'Stop' })); expect(await screen.findByRole('heading', { name: 'Scoring stopped' })).toBeInTheDocument(); });
});
