import React, { useRef, useState } from 'react';
import ToolLifecycle from './components/ToolLifecycle.jsx';

export default function App() {
  const [lead, setLead] = useState({ company: '', size: '', intent: '' }); const [state, setState] = useState('idle'); const [result, setResult] = useState(null); const [error, setError] = useState(null); const [cooldown, setCooldown] = useState(false); const controller = useRef(null); const lastSubmit = useRef(0);
  async function submit(event) { event?.preventDefault(); if (!lead.company.trim() || !lead.size || !lead.intent || state === 'loading' || cooldown || Date.now() - lastSubmit.current < 1200) return; lastSubmit.current = Date.now(); setCooldown(true); window.setTimeout(() => setCooldown(false), 1200); controller.current = new AbortController(); setState('loading'); setResult(null); setError(null); try { const response = await fetch('/.netlify/functions/score-lead', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ companyName: lead.company.trim(), companySize: lead.size, intent: lead.intent }), signal: controller.current.signal }); const payload = await response.json(); if (!response.ok) throw payload.error || { title: 'Scoring failed', message: 'The AI scoring service could not complete the request.' }; setResult(payload); setState('success'); } catch (reason) { if (reason.name === 'AbortError') { setError({ title: 'Scoring stopped', message: 'The request was cancelled before completion.' }); } else { setError({ title: reason.title || 'AI scoring unavailable', message: reason.message || 'The AI scoring service is temporarily unavailable. Please retry.' }); } setState('error'); } }
  function stop() { controller.current?.abort(); }
  return <><header className="site-header"><div className="shell"><a className="brand" href="/">Signalboard</a><span className="header-status"><i />Claude tool connection</span></div></header><main className="shell"><section className="intro"><span className="eyebrow">Lead intelligence / v1</span><h1>Turn buying signals into a next step.</h1><p>Score a lead with a structured Claude result that keeps the tool lifecycle visible from input to recommendation.</p></section><section className="workspace"><form className="lead-form" onSubmit={submit} aria-labelledby="form-title"><div><span className="eyebrow">Input</span><h2 id="form-title">Lead details</h2></div><label>Company name<input value={lead.company} maxLength={120} onChange={e => setLead({ ...lead, company: e.target.value })} placeholder="e.g. Northstar Health" required /></label><label>Company size<select value={lead.size} onChange={e => setLead({ ...lead, size: e.target.value })} required><option value="">Select size</option><option>Startup</option><option>Mid-market</option><option>Enterprise</option></select></label><label>Intent<select value={lead.intent} onChange={e => setLead({ ...lead, intent: e.target.value })} required><option value="">Select intent</option><option>Low</option><option>Medium</option><option>High</option></select></label><button className="button primary" type="submit" disabled={state === 'loading' || cooldown}>{state === 'loading' ? 'Scoring…' : cooldown ? 'Please wait…' : 'Score this lead'}</button><p className="form-note">Claude scores this lead through a protected Netlify function. No API key is sent to the browser.</p></form><ToolLifecycle state={state} lead={lead} result={result} error={error} onRetry={submit} onStop={stop} /></section></main><footer className="shell">AI scoring is handled server-side by a Netlify function.</footer></>;
}
